### ISSUE TITLE
API: reviews routers

### ISSUE THREAD

**Issue by Kieren27** [raynhlee/grace-shopper-capstone#23]
- [x] GET /reviews
- [x] GET /reviews/:username
- [x] GET /reviews/:productId
- [x] POST /reviews/:productId
- [x] PATCH /reviews/:reviewId
- [x] DELETE /reviews/:reviewId

**Comment by MtKrc** [comment]
GET /reviews
**************

const express = require('express');
const router = express.Router();
const { getAllReviews } = require('../db/models/reviews');

router.get('/reviews', async (req, res) => {
  try {
    const reviews = await getAllReviews();
    res.json(reviews);
  } catch (error) {
    console.error(error);
    res.status(500).json({ error: 'An error occurred while fetching reviews' });
  }
});

module.exports = router;

**Comment by MtKrc** [comment]
GET /reviews/:username
**************************

const express = require('express');
const router = express.Router();
const { getReviewsByUser } = require('../db/models/reviews');

router.get('/reviews/:username', async (req, res) => {
  const { username } = req.params;

  try {
    const reviews = await getReviewsByUser(username);
    res.json(reviews);
  } catch (error) {
    console.error(error);
    res.status(500).json({ error: 'An error occurred while fetching reviews' });
  }
});

module.exports = router;

**Comment by MtKrc** [comment]
GET /reviews/:productId

***************************
const express = require('express');
const router = express.Router();
const { getReviewsByProduct } = require('../db/models/reviews');

router.get('/reviews/:productId', async (req, res) => {
  const { productId } = req.params;

  try {
    const reviews = await getReviewsByProduct(productId);
    res.json(reviews);
  } catch (error) {
    console.error(error);
    res.status(500).json({ error: 'An error occurred while fetching reviews' });
  }
});

module.exports = router;

**Comment by MtKrc** [comment]
POST /reviews/:productId

******************************
const express = require('express');
const router = express.Router();
const { createReview } = require('../db/models/reviews');

router.post('/reviews/:productId', async (req, res) => {
  const { productId } = req.params;
  const { creatorId, description } = req.body;

  try {
    const review = await createReview({ creatorId, productId, description });
    res.json(review);
  } catch (error) {
    console.error(error);
    res.status(500).json({ error: 'An error occurred while creating a review' });
  }
});

module.exports = router;

**Comment by MtKrc** [comment]
PATCH /reviews/:reviewId
****************************

const express = require('express');
const router = express.Router();
const { updateReview } = require('../db/models/reviews');

router.patch('/reviews/:reviewId', async (req, res) => {
  const { reviewId } = req.params;
  const { id, ...fields } = req.body;

  try {
    await updateReview({ id: reviewId, ...fields });
    res.sendStatus(200);
  } catch (error) {
    console.error(error);
    res.status(500).json({ error: 'An error occurred while updating the review' });
  }
});

module.exports = router;

**Comment by MtKrc** [comment]
DELETE /reviews/:reviewId

******************************
const express = require('express');
const router = express.Router();
const { deleteReview } = require('../db/models/reviews');

router.delete('/reviews/:reviewId', async (req, res) => {
  const { reviewId } = req.params;

  try {
    const deletedReview = await deleteReview(reviewId);
    res.json(deletedReview);
  } catch (error) {
    console.error(error);
    res.status(500).json({ error: 'An error occurred while deleting the review' });
  }
});

module.exports = router;
